# Generated by Django 5.2.5 on 2025-09-30 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quizattempt_status_alter_quizattempt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_app.subcategory'),
        ),
    ]
