# Generated by Django 5.2.5 on 2025-10-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_quizattempt_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
