# Generated by Django 5.2.5 on 2025-10-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_quiz_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
