# Generated by Django 5.2.5 on 2025-10-06 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_quizattempt_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiz'),
        ),
    ]
