# Generated by Django 5.2.5 on 2025-10-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_remove_questionattempt_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
